version: '3.8'

x-hz-common-settings: &hz-common-settings
  image: hazelcast/hazelcast:latest
  networks:
    - hazelcast-network-0

x-common-env: &hz-common-env
  HZ_CLUSTERNAME: dev

services:
  db:
    build: db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/code/db
    networks:
      - services-network

  app:
    build: app
    environment:
      - PYTHONUNBUFFERED=0
    volumes:
      - ./app:/code/app
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - services-network

  booking:
    build: booking
    volumes:
      - ./booking:/code/booking
    ports:
      - "8080:8080"
    networks:
      - services-network
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  mongo1:
    image: mongo
    container_name: mongo1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo1-data:/data/db
    command: mongod --replSet rs0 --bind_ip 0.0.0.0 
    networks:
      - services-network

  mongo2:
    image: mongo
    restart: always
    volumes:
      - mongo2-data:/data/db
    command: mongod --replSet rs0 --bind_ip 0.0.0.0
    networks:
      - services-network

  mongo3:
    image: mongo
    restart: always
    volumes:
      - mongo3-data:/data/db
    command: mongod --replSet rs0 --bind_ip 0.0.0.0
    networks:
      - services-network

  frontend:
    build: front
    ports:
      - "8501:8501"
    volumes:
      - ./front:/code/front
    depends_on:
      - app
    networks:
      - services-network

  support1:
    build: support
    environment:
      - PYTHONUNBUFFERED=0
      - MY_PORT=81
      - HZ_NETWORK_PUBLICADDRESS=hazel-node-1:5701
      - CONTAINER_NAME=support1
    volumes:
      - ./support:/code/support
    ports:
      - "81:80"
    depends_on:
      - hazel-node-1
      - hazel-node-2
      - hazel-node-mq
      - consul
    networks:
      - services-network
      - hazelcast-network-0

  support2:
    build: support
    environment:
      - PYTHONUNBUFFERED=0
      - MY_PORT=82
      - HZ_NETWORK_PUBLICADDRESS=hazel-node-1:5701
      - CONTAINER_NAME=support2
    volumes:
      - ./support:/code/support
    ports:
      - "82:80"
    depends_on:
      - hazel-node-1
      - hazel-node-2
      - hazel-node-mq
      - consul
    networks:
      - services-network
      - hazelcast-network-0


  support-worker1:
    build: support-worker
    environment:
      - PYTHONUNBUFFERED=0
      - MY_PORT=91
      - CONTAINER_NAME=support-worker1
    volumes:
      - ./support-worker:/code/support-worker
    ports:
      - "91:80"
    depends_on:
      - hazel-node-mq
      - consul
    networks:
      - services-network
      - hazelcast-network-0


  support-worker2:
    build: support-worker
    environment:
      - PYTHONUNBUFFERED=0
      - MY_PORT=92
      - CONTAINER_NAME=support-worker2
    volumes:
      - ./support-worker:/code/support-worker
    ports:
      - "92:80"
    depends_on:
      - hazel-node-mq
      - consul
    networks:
      - services-network
      - hazelcast-network-0

#  support3:
#      build: support
#      environment:
#        - PYTHONUNBUFFERED=0
#        - MY_PORT=83
#        - HZ_NETWORK_PUBLICADDRESS=hazel-node-3:5703
#        - CONTAINER_NAME=support3
#      volumes:
#        - ./support:/code/support
#      ports:
#        - "83:80"
#      depends_on:
#        - hazel-node-1
#        - hazel-node-2
#        - hazel-node-mq
#      networks:
#        - services-network
#        - hazelcast-network-0

  gateway:
    build: gateway
    environment:
      - PYTHONUNBUFFERED=0
      - MY_PORT=85
      - CONTAINER_NAME=gateway
    volumes:
      - ./gateway:/code/gateway
    ports:
      - "85:80"
    depends_on:
      - consul
    networks:
      - services-network

  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - services-network
    command: consul agent -dev -client=0.0.0.0


  hazel-node-1:
    <<: *hz-common-settings
    container_name: hazel-node-1
    environment:
      <<: *hz-common-env
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-1:5701"
    ports:
      - "5701:5701"

  hazel-node-2:
      <<: *hz-common-settings
      container_name: hazel-node-2
      environment:
        <<: *hz-common-env
        HZ_NETWORK_PUBLICADDRESS: "hazel-node-2:5702"
      ports:
        - "5702:5701"

#  hazel-node-3:
#      <<: *hz-common-settings
#      container_name: hazel-node-3
#      environment:
#        <<: *hz-common-env
#        HZ_NETWORK_PUBLICADDRESS: "hazel-node-3:5709"
#      ports:
#        - "5709:5701"

  hazel-node-mq:
    image: hazelcast/hazelcast:latest
    container_name: hazel-node-mq
    networks:
      - services-network
    environment:
      HZ_CLUSTERNAME: mq
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-mq:5704"
    ports:
      - "5704:5701"


networks:
  hazelcast-network-0:
    driver: bridge
    name: hazelcast-network-0

  services-network:
    driver: bridge
    name: services-network

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
