version: '3.8'

x-hz-common-settings: &hz-common-settings
  image: hazelcast/hazelcast:latest
  networks:
    - hazelcast-network-0

x-hz-common-env: &hz-common-env
  HZ_CLUSTERNAME: dev

services:
  db:
    build: db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/code/db
    networks:
      - services-network

  app:
    build: app
    environment:
      - PYTHONUNBUFFERED=0
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
      - APP_SERVICE_INTERNAL_PORT=${APP_SERVICE_INTERNAL_PORT}
    volumes:
      - ./app:/code/app
    ports:
      - "80:${APP_SERVICE_INTERNAL_PORT}"
    depends_on:
      - db
      - consul
    networks:
      - services-network

  booking:
    build: booking
    volumes:
      - ./booking:/code/booking
    ports:
      - "8080:${BOOKING_SERVICE_INTERNAL_PORT}"
    networks:
      - services-network
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - consul
    environment:
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
      - BOOKING_SERVICE_INTERNAL_PORT=${BOOKING_SERVICE_INTERNAL_PORT}

  mongo1:
    image: mongo
    container_name: mongo1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo1-data:/data/db
    command: mongod --replSet rs0 --bind_ip 0.0.0.0
    networks:
      - services-network

  mongo2:
    image: mongo
    container_name: mongo2
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo2-data:/data/db
    command: mongod --replSet rs0 --bind_ip 0.0.0.0
    networks:
      - services-network

  mongo3:
    image: mongo
    container_name: mongo3
    restart: always
    ports:
      - "27019:27017"
    volumes:
      - mongo3-data:/data/db
    command: mongod --replSet rs0 --bind_ip 0.0.0.0
    networks:
      - services-network

  frontend:
    build: front
    ports:
      - "8501:8501"
    volumes:
      - ./front:/code/front
    depends_on:
      - app
    networks:
      - services-network

  support1:
    build: support
    environment:
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
      - SUPPORT_SERVICE_INTERNAL_PORT=${SUPPORT_SERVICE_INTERNAL_PORT}
      - MAPS_HZ_NETWORK_ADDRESS=hazel-node-1:5701
      - MQ_HZ_NETWORK_ADDRESS=hazel-node-mq:5704
    volumes:
      - ./support:/code/support
    ports:
      - "81:${SUPPORT_SERVICE_INTERNAL_PORT}"
    depends_on:
      - hazel-node-1
      - hazel-node-2
      - hazel-node-3
      - hazel-node-mq
      - consul
    networks:
      - services-network
      - hazelcast-network-0

  support2:
    build: support
    environment:
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
      - SUPPORT_SERVICE_INTERNAL_PORT=${SUPPORT_SERVICE_INTERNAL_PORT}
      - MAPS_HZ_NETWORK_ADDRESS=hazel-node-2:5702
      - MQ_HZ_NETWORK_ADDRESS=hazel-node-mq:5704
    volumes:
      - ./support:/code/support
    ports:
      - "82:${SUPPORT_SERVICE_INTERNAL_PORT}"
    depends_on:
      - hazel-node-1
      - hazel-node-2
      - hazel-node-3
      - hazel-node-mq
      - consul
    networks:
      - services-network
      - hazelcast-network-0

  support3:
    build: support
    environment:
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
      - SUPPORT_SERVICE_INTERNAL_PORT=${SUPPORT_SERVICE_INTERNAL_PORT}
      - MAPS_HZ_NETWORK_ADDRESS=hazel-node-3:5703
      - MQ_HZ_NETWORK_ADDRESS=hazel-node-mq:5704
    volumes:
      - ./support:/code/support
    ports:
      - "83:${SUPPORT_SERVICE_INTERNAL_PORT}"
    depends_on:
      - hazel-node-1
      - hazel-node-2
      - hazel-node-3
      - hazel-node-mq
      - consul
    networks:
      - services-network
      - hazelcast-network-0

  worker1:
    build: worker
    environment:
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
      - WORKER_SERVICE_INTERNAL_PORT=${WORKER_SERVICE_INTERNAL_PORT}
      - MAPS_HZ_NETWORK_ADDRESS=hazel-node-1:5701
      - MQ_HZ_NETWORK_ADDRESS=hazel-node-mq:5704
    volumes:
      - ./worker:/code/worker
    ports:
      - "91:${WORKER_SERVICE_INTERNAL_PORT}"
    depends_on:
      - hazel-node-1
      - hazel-node-2
      - hazel-node-3
      - hazel-node-mq
      - consul
    networks:
      - services-network
      - hazelcast-network-0

  worker2:
    build: worker
    environment:
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
      - WORKER_SERVICE_INTERNAL_PORT=${WORKER_SERVICE_INTERNAL_PORT}
      - MAPS_HZ_NETWORK_ADDRESS=hazel-node-2:5702
      - MQ_HZ_NETWORK_ADDRESS=hazel-node-mq:5704
    volumes:
      - ./worker:/code/worker
    ports:
      - "92:${WORKER_SERVICE_INTERNAL_PORT}"
    depends_on:
      - hazel-node-1
      - hazel-node-2
      - hazel-node-3
      - hazel-node-mq
      - consul
    networks:
      - services-network
      - hazelcast-network-0

  worker3:
    build: worker
    environment:
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
      - WORKER_SERVICE_INTERNAL_PORT=${WORKER_SERVICE_INTERNAL_PORT}
      - MAPS_HZ_NETWORK_ADDRESS=hazel-node-3:5703
      - MQ_HZ_NETWORK_ADDRESS=hazel-node-mq:5704
    volumes:
      - ./worker:/code/worker
    ports:
      - "93:${WORKER_SERVICE_INTERNAL_PORT}"
    depends_on:
      - hazel-node-1
      - hazel-node-2
      - hazel-node-3
      - hazel-node-mq
      - consul
    networks:
      - services-network
      - hazelcast-network-0

  gateway:
    build: gateway
    environment:
      - PYTHONUNBUFFERED=0
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    volumes:
      - ./gateway:/code/gateway
    ports:
      - "85:${GATEWAY_SERVICE_INTERNAL_PORT}"
    depends_on:
      - consul
    networks:
      - services-network

  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - services-network
    command: consul agent -dev -client=0.0.0.0

  hazel-node-1:
    <<: *hz-common-settings
    container_name: hazel-node-1
    environment:
      <<: *hz-common-env
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-1:5701"
    ports:
      - "5701:5701"
    networks:
      - hazelcast-network-0

  hazel-node-2:
    <<: *hz-common-settings
    container_name: hazel-node-2
    environment:
      <<: *hz-common-env
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-2:5702"
    ports:
      - "5702:5701"
    networks:
      - hazelcast-network-0

  hazel-node-3:
    <<: *hz-common-settings
    container_name: hazel-node-3
    environment:
      <<: *hz-common-env
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-3:5703"
    ports:
      - "5703:5701"
    networks:
      - hazelcast-network-0

  hazel-node-mq:
    <<: *hz-common-settings
    container_name: hazel-node-mq
    environment:
      HZ_CLUSTERNAME: mq
      HZ_NETWORK_PUBLICADDRESS: "hazel-node-mq:5704"
    ports:
      - "5704:5701"
    networks:
      - services-network

networks:
  hazelcast-network-0:
    driver: bridge
    name: hazelcast-network-0

  services-network:
    driver: bridge
    name: services-network

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data: